### PR TITLE
Add network param for all spaces in explore endpoint

### LINKED ISSUE #124: Add network param for all spaces in explore endpoint

### PR DESCRIPTION
**Pull request by ChaituVR**
Fixes #124

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]

**Comment by midgerate** [comment]
@ChaituVR can you merge this?

**Comment by ChaituVR** [comment]
> @ChaituVR can you merge this?

@metrox-eth Done

**Comment by metrox-eth** [comment]
> @ChaituVR can you merge this?

I think @ChaituVR wanted to tag you

**Comment by ChaituVR** [comment]
hahaha ya sorry for the wrong tag @metrox-eth 

@midgerate Done Done Done! It's merged🚀

**Pull request merged**
