### PR TITLE
commented out the currenty not used function

### PR DESCRIPTION
**Pull request by mktcode**
To make Github and my IDE stop complaining:

image

### CODE REVIEW

**Comment by ChaituVR** [comment]
I am wondering why this line is commented in the first place 🤔 how it is calculating scores for closed proposals now @bonustrack 
```
snapshot.utils.sleep(5000).then(() => run());
````

**Comment by mktcode** [comment]
Yeah I wonder now too... tbh I didn't really care and just saw that it's unused for some reason. But let me guess... on the server it's not commented out? 😃

**Comment by ChaituVR** [comment]
Maybe it is handled in some other place so commented, I don't know :D we need release notes for the hub

**Review by ChaituVR — APPROVED** [review]

**Comment by bonustrack** [comment]
@mktcode @ChaituVR This function is used to calculate score on proposals once the server start, I wouldn't comment it. This is something I enable sometime but otherwise the flow is that once a proposal is closed we get the information with events and we trigger score calculation. Here: https://github.com/snapshot-labs/snapshot-hub/blob/master/src/events/index.ts#L76

**Pull request closed without merging**
