### PR TITLE
added spaces search fields "is_admin" and "is_member"

### PR DESCRIPTION
**Pull request by mktcode**
Fixes https://github.com/snapshot-labs/snapshot/issues/871

Uses https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-contains to search in the `settings` JSON field.

Test queries:
```graphql
query AdminSpaces {
  spaces(
    where: { is_admin: "0x123..." }
  ) {
    id
    admins
    members
  }
}

query MemberSpaces {
  spaces(
    where: { is_member: "0x456..." }
  ) {
    id
    admins
    members
  }
}
```

### CODE REVIEW

**Comment by bonustrack** [comment]
Can you change `is_admin` `is_member` to `admin_contains` and `member_contains`? This is to follow subgraph syntax, the value should be an array like this `where { member_contains: ["0xe813b65da6c38a04591aed3f082d32db7d53c382"] }`

**Comment by mktcode** [comment]
@bonustrack done.

```graphql
query AdminSpaces {
  spaces(
    where: { admin_contains: ["0x123..."] }
  ) {
    id
    admins
    members
  }
}
```

Btw... someone used `JSON_OVERLAPS` before? I didn't. So you might wanna double-check that.

**Comment by bonustrack** [comment]
@mktcode It fail for me for some reason
image
See here
https://snapshot-hub-spaces-whe-2eouab.herokuapp.com/graphql?query=%0Aquery%20Spaces%20%7B%0A%20%20spaces(%0A%20%20%20%20first%3A%2020%2C%0A%20%20%20%20skip%3A%200%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20member_contains%3A%20%5B%220xeF8305E140ac520225DAf050e2f71d5fBcC543e7%22%5D%0A%20%20%20%20%7D%0A%20%20)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A

**Comment by mktcode** [comment]
Hm... running the same query locally and it works fine.

**Comment by bonustrack** [comment]
@mktcode Does it work if there isnt any result like `member_contains: ["123"]` ?

**Comment by mktcode** [comment]
I think I tried all cases. For `member_contains: ["123"]` it would return an empty array.

What about adding tests and mock data?

**Comment by bonustrack** [comment]
Any idea how to fix that query? https://snapshot-hub-spaces-whe-2eouab.herokuapp.com/graphql?query=%0Aquery%20Spaces%20%7B%0A%20%20spaces(%0A%20%20%20%20first%3A%2020%2C%0A%20%20%20%20skip%3A%200%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20member_contains%3A%20%5B%220xeF8305E140ac520225DAf050e2f71d5fBcC543e7%22%5D%0A%20%20%20%20%7D%0A%20%20)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A

**Comment by mktcode** [comment]
> Any idea how to fix that query?

Still trying to reproduce it locally.

**Comment by bonustrack** [comment]
This is not working with the MySQL version we are using. Closing for now till we find another solution

**Pull request closed without merging**
