### PR TITLE
add new endpoint to retrieve single proposal

### PR DESCRIPTION
**Pull request by jsertx**
Changes proposed in this pull request:
- Add new endpoint /:space/proposals/:id to get a single proposal following.

### CODE REVIEW

**Comment by bonustrack** [comment]
@jsertx Hey thank you for the PR! Curious to know what is your use case? We are working on a GraphQL API here: https://hub.snapshot.page/graphql I would prefer to not introduce new Rest API endpoint and reuse the GraphQL `timeline` function to get a single proposal.

**Comment by jsertx** [comment]
Hi @bonustrack I do not have a rare usecase, I just wanted to be able to fetch a single proposal to not fetch all proposals and filter in the client, I will take a look at the graphql API.

**Comment by bonustrack** [comment]
@jsertx Here is an example on how to load a single proposal using GraphQL https://hub.snapshot.page/graphql?query=query%20Timeline%20%7B%0A%20%20timeline(id%3A%20%22QmRcDskfVtaCuAL6KGYtyQyVMn2qx5QL76qP4tw2GdAD1J%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20body%0A%20%20%20%20start%0A%20%20%20%20end%0A%20%20%20%20state%0A%20%20%20%20author%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A Another way to do this is to directly load the proposal from IPFS, like this https://ipfs.io/ipfs/QmRcDskfVtaCuAL6KGYtyQyVMn2qx5QL76qP4tw2GdAD1J

**Comment by jsertx** [comment]
> @jsertx Here is an example on how to load a single proposal using GraphQL https://hub.snapshot.page/graphql?query=query%20Timeline%20%7B%0A%20%20timeline(id%3A%20%22QmRcDskfVtaCuAL6KGYtyQyVMn2qx5QL76qP4tw2GdAD1J%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20body%0A%20%20%20%20start%0A%20%20%20%20end%0A%20%20%20%20state%0A%20%20%20%20author%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A Another way to do this is to directly load the proposal from IPFS, like this https://ipfs.io/ipfs/QmRcDskfVtaCuAL6KGYtyQyVMn2qx5QL76qP4tw2GdAD1J

Thanks, it was helpful!

**Pull request closed without merging**
