### PR TITLE
Add validations to explore

### PR DESCRIPTION
**Pull request by ChaituVR**

### CODE REVIEW

**Comment by ChaituVR** [comment]
[Add validations spaces to explore endpoint](https://trello.com/c/UpeGLXtc/315-add-validations-spaces-to-explore-endpoint)

**Comment by bonustrack** [comment]
Whats the need of this?

**Comment by ChaituVR** [comment]
@samuveth

**Comment by samuveth** [comment]
@bonustrack we need the number of spaces that are using each validation. Like we have with strategies, skins ...

**Comment by bonustrack** [comment]
Ok yes but on this PR it give the validation for each space, it doesnt show the validation count for each validation id. @ChaituVR Can you remove this change and instead show count like
```
...
validations: {
  basic: 1251
  aave: 1
}
```

**Comment by ChaituVR** [comment]
Should be fine now :) just got confused with Trello card title

**Review by bonustrack — APPROVED** [review]

**Comment by samuveth** [comment]
@bonustrack @ChaituVR  I'm not getting a validation object on the explore endpoint. 
image

**Comment by bonustrack** [comment]
@samuveth Its just merged it should show up in 2mn

**Comment by bonustrack** [comment]
Works already 
image

**Pull request merged**
