### PR TITLE
Unique voters in one day

### LINKED ISSUE #114: Add voters and voters_1d count per space on explore endpoint

### PR DESCRIPTION
**Pull request by ChaituVR**
Fixes #114

### CODE REVIEW

**Comment by bonustrack** [comment]
@ChaituVR I tried to vote on demo site and wait few mn but cant see it on https://snapshot-hub-voters-1d-hk67aut.herokuapp.com/api/explore for some reason

**Comment by ChaituVR** [comment]
@bonustrack I tried voting on your space and the count increased 
image

Maybe you voted on a proposal that you previously voted few days back?? 🤔

**Comment by bonustrack** [comment]
@ChaituVR That's right but why it wouldn't count, isn't the query asking for last day vote?

**Comment by ChaituVR** [comment]
I just tried voting on a proposal that I voted for previously and it works, shows count on voters_1d

**Comment by ChaituVR** [comment]
I am voting on this proposal https://demo.snapshot.org/#/fabien.eth/proposal/0xe369a3e58e1e8993432742f039b3b63a31ff3202d4638299d09d09f4884e31c9

maybe can you share an example where count is not added up?

**Review by bonustrack — APPROVED** [review]
Ok i've tested it works well

**Pull request merged**
