### PR TITLE
fix: Reduce wait time to two mins while loading spaces

### PR DESCRIPTION
**Pull request by ChaituVR**
Reducing wait time to 2 mins from 6 mins, as 6 mins is quite high and it feels like something is down

### CODE REVIEW

**Comment by wa0x6e** [comment]
Why would it feels like something is down ? This function is run immediately on server start

**Comment by ChaituVR** [comment]
> Why would it feels like something is down ? This function is run immediately on server start

No not on server start, but try going to https://testnet.snapshot.org/#/ and follow a space 😄 it takes very long to see correct followers, i think these functions `loadSpaces` `loadSpacesMetrics` take long time on prod anyway, I feel waiting for 6 mins doesn't make anything better.

**Comment by wa0x6e** [comment]
I see now. Theses counters will be faster with https://github.com/orgs/snapshot-labs/projects/12/views/1?pane=issue&itemId=55693630 later, and this `run()` should only updates space scores used for sorting

**Review by wa0x6e — APPROVED** [review]
utAck

**Pull request merged**
