### PR TITLE
Add event emitter caching for votes

### PR DESCRIPTION
**Pull request by bonustrack**

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
Why just `votes`? can be applied to all other queries too right?

**Comment by mktcode** [comment]
I assume `ee.ts` stands for (not sure how to name this file but something with) event emitter? But `eventEmitter.ts` didn't feel perfectly right, because it's not really an event emitter but instead uses one to debounce responses? How about `debounceResponse.ts` then? 😃

**Comment by bonustrack** [comment]
@ChaituVR We can apply it to others queries, I just want to test in votes first, I believe that the most heavy queries

**Comment by bonustrack** [comment]
@mktcode Isn't better to use debounce request instead of response? Maybe just "debounce" since it could be used anywhere?

**Comment by bonustrack** [comment]
I'll merge this first anyway

**Pull request merged**
