### PR TITLE
feat: add support for new statement properties

### PR DESCRIPTION
**Pull request by wa0x6e**
Related to https://github.com/snapshot-labs/sx-monorepo/pull/407

Return new statement properties

### CODE REVIEW

**Comment by ChaituVR** [comment]
Whats the SQL command to change prod DB?

**Comment by ChaituVR** [comment]
wdyt about 
```SQL
ALTER TABLE statements
MODIFY id VARCHAR(66) NOT NULL,
MODIFY delegate VARCHAR(100) NOT NULL,
MODIFY space VARCHAR(100) NOT NULL,
ADD COLUMN network VARCHAR(24) NOT NULL DEFAULT 's',
ADD COLUMN discourse VARCHAR(64),
ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'inactive',
DROP PRIMARY KEY,
ADD PRIMARY KEY (delegate, space, network),
ADD INDEX space (space),
ADD INDEX network (network),
ADD INDEX status (status);
```

**Comment by wa0x6e** [comment]
> why default to `inactive`?

Decided by Fabien

**Comment by wa0x6e** [comment]
> wdyt about
> 
> ```sql
> ALTER TABLE statements
> MODIFY id VARCHAR(66) NOT NULL,
> MODIFY delegate VARCHAR(100) NOT NULL,
> MODIFY space VARCHAR(100) NOT NULL,
> ADD COLUMN network VARCHAR(24) NOT NULL DEFAULT 's',
> ADD COLUMN discourse VARCHAR(64),
> ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'inactive',
> DROP PRIMARY KEY,
> ADD PRIMARY KEY (delegate, space, network),
> ADD INDEX space (space),
> ADD INDEX network (network),
> ADD INDEX status (status);
> ```

Seems good. Maybe also proceed to the COLLATON change, since this table is small, and not related to anything else

**Review by ChaituVR — APPROVED** [review]
utAck

**Pull request merged**
