### PR TITLE
added support for older eip1271 implementations

### PR DESCRIPTION
**Pull request by poocart**
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/37.

Changes proposed in this pull request:
- Added legacy EIP1271 implementation ABI to support related Smart Contract wallets.

### CODE REVIEW

**Comment by bonustrack** [comment]
@poocart I'm not able to test vote on snapshot.org using Pillar Wallet with WalletConnect, when i try to vote i don't get prompted to confirm signing a message on Pillar Wallet. Anything i should be aware? Can you help me troubleshoot?

**Comment by bonustrack** [comment]
@poocart I can see now that it will require to spend some ETH to setup the smart wallet, is there an easier way to test it?

**Comment by poocart** [comment]
> @poocart I can see now that it will require to spend some ETH to setup the smart wallet, is there an easier way to test it?

Hey @bonustrack ! Yes, unfortunately EIP-1271 works only with deployed contract accounts. We at Pillar can provide you one you can test with, how we can reach you outside GitHub?

**Comment by bonustrack** [comment]
@poocart i'm on Telegram my username is `@bonustrack`

**Review by bonustrack — APPROVED** [review]
Just been able to test with Pillar and it's working well! Thank you for your contribution

**Pull request merged**
